config/routes.rb
Rails.application.routes.draw do

  root :to => "home#homepage"
  get "users/signed_out" => "authentication#signed_out"
  get "users/:id/signed_out" => "authentication#signed_out"
  get "signed_out" => "authentication#signed_out"
  get "sign_in" => "authentication#sign_in"
  get "sign_up" => "users#new"
  get "users/:user_id/documents" => "documents#show_documents_of_user"
  get "groups/:group_id/documents" => "documents#show_documents_in_group"
  get "addOrDeleteDocuments" => "groups#add_delete_documents"
  post "sign_in" => "authentication#login"
  post "sign_up" => "users#create"

  resources :group_docs

  resources :documents

  resources :user_groups

  resources :groups do
    resources :documents , only: [:index, :show, :update]
  end

  resources :users do
    resources :documents, only: [:index, :show]
  end

end

app/models/user_group.rb
class UserGroupValidator < ActiveModel::Validator
  def validate(record)
    if User.where("id = '#{record.user_id}'").size == 0
      record.errors[:base] << "No such a record."
    end
    if Group.where("id = '#{record.group_id}'").size == 0
      record.errors[:base] << "No such a record."
    end
  end
end


class UserGroup < ActiveRecord::Base
  
  belongs_to :user, :foreign_key=> :user_id
  belongs_to :group, :foreign_key=> :group_id
  self.primary_keys = :user_id, :group_id
  validates :group_id, uniqueness: { scope: :user_id}, presence:true
  validates :user_id, uniqueness: { scope: :group_id}, presence:true
  
  validates_with UserGroupValidator
  
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]
  before_filter :check_privileges!
  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end
  

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:user_id, :group_id)
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.text_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing user_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<h1>Listing user_groups</h1>

<table>
  <thead>
    <tr>
      <th>Group ID</th>
      <th>Group Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_groups.each do |user_group| %>
      <tr>
        <td><%= user_group.group_id %></td>
        <% group = Group.find_by_id(user_group.group_id) %>
        <td><%= group.group_name %></td>
        <td><%= group.created_at %></td>
        <td><%= group.updated_at %></td>
        <td><%= link_to 'Show', user_group %></td>
        <td><%= link_to 'Edit', edit_user_group_path(user_group) %></td>
        <td><%= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/new.html.erb
<h1>New user_group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pennkey:</strong>
  <%= @user_group.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @user_group.group_id %>
</p>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>