config/routes.rb
Rails.application.routes.draw do

  root :to => "home#homepage"
  get "users/signed_out" => "authentication#signed_out"
  get "users/:id/signed_out" => "authentication#signed_out"
  get "signed_out" => "authentication#signed_out"
  get "sign_in" => "authentication#sign_in"
  get "sign_up" => "users#new"
  get "users/:user_id/documents" => "documents#show_documents_of_user"
  get "groups/:group_id/documents" => "documents#show_documents_in_group"
  get "addOrDeleteDocuments" => "groups#add_delete_documents"
  post "sign_in" => "authentication#login"
  post "sign_up" => "users#create"

  resources :group_docs

  resources :documents

  resources :user_groups

  resources :groups do
    resources :documents , only: [:index, :show, :update]
  end

  resources :users do
    resources :documents, only: [:index, :show]
  end

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :user_groups, :dependent => :destroy
  has_many :users, through: :user_groups
  
  has_many :group_docs, :dependent => :destroy
  has_many :documents, through: :group_docs

  validates :group_name, uniqueness: true, presence:true
  
  
  def changeAccessibleDocs(doc_ids)
    
    GroupDoc.where(group_id:self.id).each do |gd|
      gd.destroy
    end
    
    doc_ids.each do |di|
      GroupDoc.create(group_id:self.id, document_id:di)
    end
    
  end
  
  def changeUsers(user_ids)
    
    UserGroup.where(group_id:self.id).each do |ug|
      ug.destroy
    end
    
    user_ids.each do |ui|
      UserGroup.create(group_id:self.id, user_id:ui)
    end
    
  end
  
  
  
  
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_filter :check_privileges!
  # GET /groups
  # GET /groups.json

  def add_delete_documents
    document_ids = params[:document_ids].split(',')
    group = Group.find_by_id(params[:group_id])
    group.changeAccessibleDocs(document_ids)
    redirect_to group_documents_path(group)
  end

  def index
    @groups = Group.all
    @group_docs = get_all_docs
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @all_documents = Document.all
    @group_documents = Group.find_by_id(params[:id]).documents
    @group = Group.find_by_id(params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end
 

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name)
    end

    def get_all_docs
      groups = Group.all
      result_documents = { }
      groups.each do |group|
        result_documents[group.id] = group.documents
      end
      return result_documents
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_name %><br>
    <%= f.text_field :group_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Existing Groups</h3>
  </div>
  <div class="panel-body">
    <p>All groups with the number of documents in them</p>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="list-group">
        <div class="row">
          <div class="col-md-8"><a href="#" class="list-group-item active">Group Name</a></div>
       <!--   <div class="col-md-4"><a href="#" class="list-group-item">Action</a></div>   -->
        </div>
        <% @groups.each do |group| %>
            <div class="row">
              <div class="col-md-8"><a href= <%= 'groups/' + group.id.to_s%> class="list-group-item">
                <span class="badge"><%=@group_docs[group.id].size%></span>
                <%= group.group_name %></a>
              </div>
              <div class="col-md-4">
                <div class="col-md-4"><%= link_to 'Show', group_documents_path(group) , {class: ["btn btn-primary ", "container-fluid"]}%></div>
                <div class="col-md-4"><%= link_to 'Edit', group_url(group), {class: "btn btn-info " }%></div>
                <div class="col-md-4"><%= link_to 'Delete', group, {class: "btn btn-danger ", method: :delete, data: { confirm: 'Are you sure?' }} %></div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-4"><a href="#" class="list-group-item">Documents</a></div>
  </div>

</div>


<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center"><h3>Change Group: <%=@group.group_name%> Documents</h3></div>
    <div class="col-sm-4 col-sm-offset-1">
      <div class="list-group" id="list1">
        <a href="#" class="list-group-item active">Existing Documents <input title="toggle all" type="checkbox" class="all pull-right"></a>
        <% @all_documents.each do |document| %>
            <a href= "#" class="list-group-item" ><%= document.document_name %><input type="checkbox" class="pull-right" value = <%=document.id%>></a>
        <% end %>
      </div>
    </div>
    <div class="col-md-2 v-center">
      <button title="Send to list 2" class="btn btn-default center-block add"><i class="glyphicon glyphicon-chevron-right"></i></button>
      <button title="Send to list 1" class="btn btn-default center-block remove"><i class="glyphicon glyphicon-chevron-left"></i></button>
      <button title="Save Change" class="btn btn-primary center-block save">Save</button>
    </div>
    <div class="col-sm-4">
      <div class="list-group" id="list2">
        <a href="#" class="list-group-item active">Current Documents<input title="toggle all" type="checkbox" class="all pull-right"></a>
        <% @group_documents.each do |document| %>
            <a href= "#" class="list-group-item" value = <%=document.id%> ><%=document.document_name %> <input type="checkbox" class="pull-right" value = <%=document.id%>></a>
        <% end %>
      </div>
    </div>
  </div>

</div>

<script type="text/javascript">
    $('.add').click(function(){
        $('.all').prop("checked",false);
        var items = $("#list1 input:checked:not('.all')");
        var n = items.length;
        if (n > 0) {
            var hashmap = {};
            var items2 = $("#list2 input:checkbox:not('.all')");
            items2.each(function(idx,item){
        //        console.log($(item), 111);
                hashmap[$(item).val()] = true;
            });
        //    console.log(hashmap, 111);
            items.each(function(idx,item){
                var choice = $(item);
                choice.prop("checked",false);
        //        console.log(choice.val(),111);
                console.log(hashmap[choice.val()],111);
                if (hashmap[choice.val()] === true) {
                    choice.parent().remove();
                }else{
                    choice.parent().appendTo("#list2");
                }
            });
        }
        else {
            alert("Choose an item from list 1");
        }
    });

    $('.remove').click(function(){
        $('.all').prop("checked",false);
        var items = $("#list2 input:checked:not('.all')");
        var hashmap = {};
        var items1 = $("#list1 input:checkbox:not('.all')");
        items1.each(function(idx,item){
            //        console.log($(item), 111);
            hashmap[$(item).val()] = true;
        });
        items.each(function(idx,item){
            var choice = $(item);
            choice.prop("checked",false);
            if (hashmap[choice.val()] === true) {
                choice.parent().remove();
            }else{
                choice.parent().appendTo("#list1");
            }
        });
    });

    $('.save').click(function(){
        var document_ids = [];
        var items = $("#list2 input:checkbox:not('.all')");
        items.each(function(idx,item){
            var choice = $(item);
            document_ids.push(choice.val());
            var group_id = <%=@group.id%>
            window.location = '../addOrDeleteDocuments?group_id=' + group_id + '&document_ids=' + document_ids;
        });
    });

    /* toggle all checkboxes in group */
    $('.all').click(function(e){
        e.stopPropagation();
        var $this = $(this);
        if($this.is(":checked")) {
            $this.parents('.list-group').find("[type=checkbox]").prop("checked",true);
        }
        else {
            $this.parents('.list-group').find("[type=checkbox]").prop("checked",false);
            $this.prop("checked",false);
        }
    });

    $('[type=checkbox]').click(function(e){
        e.stopPropagation();
    });

    /* toggle checkbox when list group item is clicked */
    $('.list-group a').click(function(e){

        e.stopPropagation();

        var $this = $(this).find("[type=checkbox]");
        if($this.is(":checked")) {
            $this.prop("checked",false);
        }
        else {
            $this.prop("checked",true);
        }

        if ($this.hasClass("all")) {
            $this.trigger('click');
        }
    });
</script>