config/routes.rb
Rails.application.routes.draw do

  root :to => "home#homepage"
  get "users/signed_out" => "authentication#signed_out"
  get "users/:id/signed_out" => "authentication#signed_out"
  get "signed_out" => "authentication#signed_out"
  get "sign_in" => "authentication#sign_in"
  get "sign_up" => "users#new"
  get "users/:user_id/documents" => "documents#show_documents_of_user"
  get "groups/:group_id/documents" => "documents#show_documents_in_group"
  get "addOrDeleteDocuments" => "groups#add_delete_documents"
  post "sign_in" => "authentication#login"
  post "sign_up" => "users#create"

  resources :group_docs

  resources :documents

  resources :user_groups

  resources :groups do
    resources :documents , only: [:index, :show, :update]
  end

  resources :users do
    resources :documents, only: [:index, :show]
  end

end

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade in">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= message %>
    </div>
<% end %>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%=root_url%> >Crisis Management</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%url = '#'%>
        <%url = user_documents_url(current_user) if current_user%>
        <li ><a class="navbar-brand" href= <%=url%> >Documents <span class="sr-only">(current)</span></a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user == nil%>
            <a class="btn btn-primary navbar-btn active" type="button" href="sign_up">Sign up</a>
            <a class="btn btn-primary navbar-btn active" type="button" href="sign_in">Sign in</a>
        <% else%>
            <% if current_user.privilege == 0 or current_user.privilege == 1%>
              <li><a class="navbar-brand" href= <%= users_url %>>Users</a></li>
              <li><a class="navbar-brand" href= <%= groups_url %>>Groups</a></li>
            <% else %>
          <!--    <li><a class="navbar-brand" href= #>Link</a></li>  -->
            <% end %>
            <li class="dropdown">
              <a class="navbar-brand" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href= <%= user_path(current_user)%>>Profile</a></li>
                <li><a href="#">Contact Admin</a></li>
                <li class="divider"></li>
                <li><a href="/signed_out">Sign out</a></li>
              </ul>
            </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>