config/routes.rb
Rails.application.routes.draw do

  root :to => "home#homepage"
  get "users/signed_out" => "authentication#signed_out"
  get "users/:id/signed_out" => "authentication#signed_out"
  get "signed_out" => "authentication#signed_out"
  get "sign_in" => "authentication#sign_in"
  get "sign_up" => "users#new"
  get "users/:user_id/documents" => "documents#show_documents_of_user"
  get "groups/:group_id/documents" => "documents#show_documents_in_group"
  get "addOrDeleteDocuments" => "groups#add_delete_documents"
  post "sign_in" => "authentication#login"
  post "sign_up" => "users#create"

  resources :group_docs

  resources :documents

  resources :user_groups

  resources :groups do
    resources :documents , only: [:index, :show, :update]
  end

  resources :users do
    resources :documents, only: [:index, :show]
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  
  has_many :group_docs, :dependent => :destroy
  has_many :groups, through: :group_docs
  
  validate :document_name, presence: true, uniqueness: true
  validate :url, presence: true
  

  def users
    result_users = []
    self.groups.each do |g|
      g.users.each do |u|
        result_users << u
      end
    end
    return result_users.to_set
    
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  before_filter :check_privileges!, only: [:new, :create, :destroy]
  # GET /documents
  # GET /documents.json
  def show_documents_in_group
    group = Group.find_by_id(params[:group_id])
    @documents = group.documents
    @tag = 1
    render :index
  end

  def show_documents_of_user
    if !current_user
      redirect_to root_url
    else
      @tag = 2
      if is_admin?
        @documents = Document.all
      else
        @documents = current_user.documents
      end
      render :index
    end

  end

  def index

  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:document_name, :url)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :document_name %><br>
    <%= f.text_field :document_name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/admin.html.erb
<h1>Admin user homepage</h1>
<ul>
  <li><a href="my_pdf_file.pdf">PDF 1</a>   <button> view </button></li>
  <li><a href="my_pdf_file.pdf">PDF 2</a>   <button> view </button></li>
  <li><a href="my_pdf_file.pdf">PDF 3</a>   <button> view </button></li>
</ul>


<h2>List of current users</h2>
<table>
  <tr>
    <th>name</th>
    <th>permission</th>
  </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%=user.pennkey.to_s %></td>
        <td><%=user.level.to_s %></td>
      </tr>

    <% end %>
</table>

app/views/documents/document.html.erb
<h1>Documents</h1>
<ul>
  <li><a href="my_pdf_file.pdf">PDF 1</a>   <button> view </button></li>
  <li><a href="my_pdf_file.pdf">PDF 2</a>   <button> view </button></li>
  <li><a href="my_pdf_file.pdf">PDF 3</a>   <button> view </button></li>
</ul>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<div class="page-header">
  <%if @tag == 1%>
      <h1>Current documents<small> Listed are the documents in current group</small></h1>
  <% else %>
      <h1>Current documents<small> Listed are the documents you can view</small></h1>
  <% end %>

</div>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Documents</h3>
  </div>
  <div class="list-group">
    <div class="row">
      <div class="col-md-8"><a href="#" class="list-group-item">Document Name</a></div>
    </div>
    <% @documents.each do |document| %>
      <div class="row">
        <div class="col-md-8"><a href= <%= 'documents/' + document.id.to_s%> class="list-group-item"><%= document.document_name %></a></div>
        <div class="col-md-1"><%= link_to 'Show', document , {class: "btn btn-primary "}%></div>
        <div class="col-md-1"><%= link_to 'Edit', edit_document_path(document), {class: "btn btn-info " }%></div>
        <div class="col-md-1"><%= link_to 'Delete', document, {class: "btn btn-danger ", method: :delete, data: { confirm: 'Are you sure?' }} %></div>
      </div>
    <% end %>
  </div>

</div>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/readonly.html.erb
<h1>Readonly user homepage</h1>
<ul>
  <li><a href="my_pdf_file.pdf">PDF 1</a>   <button> view </button></li>
  <li><a href="my_pdf_file.pdf">PDF 2</a>   <button> view </button></li>
  <li><a href="my_pdf_file.pdf">PDF 3</a>   <button> view </button></li>
</ul>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document name:</strong>
  <%= @document.document_name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @document.url %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/documents/writeable.html.erb
<h1>Writeable user homepage</h1>
<ul>
  <li><a href="my_pdf_file.pdf">PDF 1</a>   <button> view </button> <button> edit </button></li>
  <li><a href="my_pdf_file.pdf">PDF 2</a>   <button> view </button> <button> edit </button></li>
  <li><a href="my_pdf_file.pdf">PDF 3</a>   <button> view </button> <button> edit </button></li>
</ul>